spring.application.name=authentication
server.port=8081
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/transversaleCommerce}
jwt.secret=${JWT_SECRET:ECommerceSecret123}


spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
# Eureka — forcer l'enregistrement sur localhost (dev local)
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
