spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: authentication-api
          uri: lb://authentication
          predicates:
            - Path=/authentication/api/**
          filters:
            - RewritePath=/authentication/(?<segment>.*), /$\{segment}

        - id: authentication-swagger
          uri: lb://authentication
          predicates:
            - Path=/authentication/v3/api-docs, /authentication/swagger-ui/**, /authentication/swagger-ui.html
          filters:
            - RewritePath=/authentication/(?<segment>.*), /$\{segment}

        - id: customer-service-api
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/api/**
          filters:
            - RewritePath=/customer-service/(?<segment>.*), /$\{segment}

        - id: customer-service-swagger
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/v3/api-docs, /customer-service/swagger-ui/**, /customer-service/swagger-ui.html
          filters:
            - RewritePath=/customer-service/(?<segment>.*), /$\{segment}

        - id: product-service-api
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/**
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

        - id: product-service-swagger
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs, /product-service/swagger-ui/**, /product-service/swagger-ui.html
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

        - id: avis-service-api
          uri: lb://avis-service
          predicates:
            - Path=/avis-service/api/**
          filters:
            - RewritePath=/avis-service/(?<segment>.*), /$\{segment}

        - id: avis-service-swagger
          uri: lb://avis-service
          predicates:
            - Path=/avis-service/v3/api-docs, /avis-service/swagger-ui/**, /avis-service/swagger-ui.html
          filters:
            - RewritePath=/avis-service/(?<segment>.*), /$\{segment}

        - id: search-service-api
          uri: http://proj-search:8088
          predicates:
            - Path=/search-service/api/**
          filters:
            - RewritePath=/search-service/(?<segment>.*), /$\{segment}

        - id: search-service-swagger
          uri: http://proj-search:8088
          predicates:
            - Path=/search-service/v3/api-docs, /search-service/swagger-ui/**, /search-service/swagger-ui.html
          filters:
            - RewritePath=/search-service/(?<segment>.*), /$\{segment}

        - id: recommendation-service-api
          uri: http://proj-recommendation:8090
          predicates:
            - Path=/recommendation-service/api/**
          filters:
            - RewritePath=/recommendation-service/(?<segment>.*), /$\{segment}

        - id: message-service-api
          uri: lb://message-service
          predicates:
            - Path=/message-service/api/**
          filters:
            - RewritePath=/message-service/(?<segment>.*), /$\{segment}

        - id: message-service-ws
          uri: lb:ws://message-service
          predicates:
            - Path=/message-service/ws/**
          filters:
            - RewritePath=/message-service/(?<segment>.*), /$\{segment}

        - id: message-service-swagger
          uri: lb://message-service
          predicates:
            - Path=/message-service/v3/api-docs, /message-service/swagger-ui/**, /message-service/swagger-ui.html
          filters:
            - RewritePath=/message-service/(?<segment>.*), /$\{segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
