spring.application.name=product-service
server.port=8082
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/transversaleProducts}
jwt.secret=${JWT_SECRET:ECommerceSecret123}

spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=true